services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: ["postgres", "-c", "log_statement=all", "-c", "log_duration=on"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./migrations/migrate.sql:/docker-entrypoint-initdb.d/migrate.sql
      - postgres_data:/var/lib/postgresql
  app:
      depends_on:
        postgres:
          condition: service_healthy
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "50051:50051"
      env_file:
        - .env
  bot:
    depends_on: 
      app:
        condition: service_started
      redis:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file:
     - .env
  redis:
    image: redis:8.8.1
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${RDB_PWD}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${RDB_PWD} ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: